package factory.method;

import concret.product.*;
import concrete.creator.*;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import guardar.*;

public class Frame extends javax.swing.JFrame {

    Application app;
    IGuardar guardar;
    ConnectionMannager cm;
    int connect;
    boolean c;
     
    public Frame() {
        initComponents();
        connect = JOptionPane.showConfirmDialog(null, "¿Tiene conexión?", "Verificación", JOptionPane.YES_NO_OPTION);
        c = cm.conectar(connect);
        if (c == true) {
            guardar = HardDisk.getDisk();
        } else {
            guardar = ExternalServer.getServer();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboApp = new javax.swing.JComboBox();
        btnSaliir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el tipo de aplicacion que desea crear:");

        comboApp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Aplicación de dibujo", "Aplicación de editor de texto", "Aplicación de presenación" }));
        comboApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAppActionPerformed(evt);
            }
        });

        btnSaliir.setText("Salir");
        btnSaliir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaliirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(comboApp, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnSaliir)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSaliir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAppActionPerformed
        String opc = comboApp.getSelectedItem().toString();
        switch (opc) {            
            case "Seleccionar":
                JOptionPane.showMessageDialog(rootPane, "Por favor seleccione un tipo de aplicación", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "Aplicación de dibujo":                              
                app = new DrawingApplication();                
                DrawingDocument drawDoc = (DrawingDocument) app.createDocument();                       
                guardar.save(drawDoc);
                drawDoc.open();
                break;
            case "Aplicación de editor de texto":
                app = new TextEditorApplication();
                TextDocument TxtDocument = (TextDocument) app.createDocument();                
                TxtDocument.open();
                break;
            case "Aplicación de presenación":
                app = new PresentationApplication();
                PresentationDocument pstDocument = (PresentationDocument) app.createDocument();                
                pstDocument.open();
                break;
        }
    }//GEN-LAST:event_comboAppActionPerformed

    private void btnSaliirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaliirActionPerformed
        exit(0);
    }//GEN-LAST:event_btnSaliirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaliir;
    private javax.swing.JComboBox comboApp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
